version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    env_file: 
      - ./.env
    environment:
      WORDPRESS_DB_HOST: $DB_HOST
      WORDPRESS_DB_USER: $DB_USERNAME
      WORDPRESS_DB_PASSWORD: $DB_PWD
      WORDPRESS_DB_NAME: $DB_NAME
    volumes:
      - wordpress:/var/www/html
    networks:
      - traefik-public
      - sql-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.rule=Host(`$WORDPRESS_URL`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"

volumes:
  wordpress:

networks:
  sql-net:
    external: true
  traefik-public:
    external: true